build:
  image: python:3.6.0-alpine
  commands:
    - ls -al
    - pwd
    - pip install --upgrade pip setuptools wheel
    - pip wheel -r requirements.txt --wheel-dir=wheeldir --find-links=wheeldir
    - pip wheel -r test-requirements.txt --wheel-dir=wheeldir --find-links=wheeldir
    - pip install --use-wheel --no-index --find-links=wheeldir -r requirements.txt
    - pip install --use-wheel --no-index --find-links=wheeldir -r test-requirements.txt
